### ISSUE TITLE
[Bug] Login page and Register page has blank white space below, after removing simpleFooter.js

### ISSUE THREAD

**Issue by pavankpdev** [creativetimofficial/argon-design-system-react#20]
### Version
latest
### Reproduction link
https://romantic-goodall-98a83e.netlify.app/auth/register
### Operating System
windows 10 pro 64bit
### Device
PC
### Browser & Version
chrome latest
### Steps to reproduce
1. Guidance on modifying the CSS property to get rid of that white space.
### What is expected?
Full page gradient background with shapes and my register/login form. 
### What is actually happening?
I used the demo login page provided with the design system, I removed the footer component, now the footer component is removed but the white space still exist.

---
### Additional comments
Please let me know which CSS property to edit get rid of that white space.
I've added a netlify link above kindly visit that link and scroll below to see the white space.

**Comment by einazare** [comment]
Hello there, @pavankpdev ,

Thank you for your interest in working with our products.
In our product, Argon Design System React, we do not make use of CSS, but of SCSS.
Also, the link you have given us, redirects us to the following:
<img width="1914" alt="Screen Shot 2020-08-29 at 2 12 04 PM" src="https://user-images.githubusercontent.com/26245512/91635496-a443e000-ea01-11ea-8649-edf4ce7057de.png">
Please provide us with a functioning link next time, or we will ignore your issue.
To solve your issue, you only need to add the following bit of css/scss:
```
.section.section-shaped {
     height: 100vh !important;
}
```

I will close this issue now, since our page was created to function with the footer, not without it.

Best,
Manu
